### QUICK REVISION NOTES 9

## What is NumPy

In [ ]:
# NumPy stands for numerical python, which is used for working with arrays
# An array is a collection of items stored at contiguous memory locations.
# They are called as ndarrays (n-dimensional arrays)
# The idea is to store multiple items of the same type together.

### Why is NumPy array is faster than list

In [ ]:
# NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.
# NumPy is capable of storing only the homogeneous datatypes in contiguous memory location.
# This makes the calculation / processing faster in numpy
# But list is only capabale of storing hetrogeneous datatypes in non-contigious memory location.

### Importing and using numpy

In [1]:
import numpy as np     # Importing numpy library
print(np.__version__)  # To check numpy version
print(len(dir(np)))    # number of functions available within numpy

1.19.2
623


### Creating a numpy array

In [5]:
# creating array using np.array(list)

arr = np.array([20,30,40])  # craeting a numpy array
print(arr)
print(arr.dtype)  # to check the datatype of the array
print(type(arr))  # tells us the type of the object passed to it

[20 30 40]
int64
<class 'numpy.ndarray'>


In [90]:
# creating array using np.arange(start, stop, step)  # returns int

# by default start is 0 and stop is n-1 and step is 1
ara = np.arange(20) 
print(ara)
print(ara.dtype)  
print(type(ara))
print()

ara2 = np.arange(0,100,10)
print(ara2)
print(ara2.dtype)  
print(type(ara2))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
int64
<class 'numpy.ndarray'>

[ 0 10 20 30 40 50 60 70 80 90]
int64
<class 'numpy.ndarray'>


In [109]:
# creating array using np.linspace(start, stop, no.of.division)  # returns float

# it requires start and stop, by default no.of.division is 50. Unlike arange here stop value is n.
lar = np.linspace(1,10)  # 50 division between 1 and 10
print(lar)
print()

ular = np.linspace(1,2,6) # 5 division between 1 and 2
print(ular)

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]

[1.  1.2 1.4 1.6 1.8 2. ]


In [177]:
# creating array using np.zeros()
print('Array using np.zeros(shape, dtype=float)')
zar = np.zeros((5,3),dtype=int)
print(zar)

# creating array using np.ones()
print('\nArray using np.ones(shape, dtype=float)')
oar = np.ones((2,5,5),dtype=int)
print(oar)

# creating array using np.eye()
print('\nArray using np.eye(N= no.of.row, M= no.of.column, k=0)')
# k represents to the diagonal type, by default it main diagonal.
# negative k value refers lower diagonal eye matrix value refers upper diagonal eye matrix
ear = np.eye(5,4,-1)
print(ear)

# creating empty array
print('\nEmpty array without initializing elements')
marr = np.empty((5,2))
print(marr)

# creating a full array using np.full
print('\nFull array using np.full(shape, fill_value, dtype=None)')
far  = np.full((2,3),(8))
far1 = np.full((5,2),(3,8))
far2 = np.full((5,2),((3,8),(9,2),(3,8),(9,2),(1,1)))
print(far)
print('\n',far1)
print('\n',far2)

# creating a random array elements
print('\nCreating a random array using np.random.rand()')
rar = np.random.rand(5,2)
rar1 = np.random.rand(2,3,3)
print(rar)
print('\n', rar1)

Array using np.zeros(shape, dtype=float)
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]

Array using np.ones(shape, dtype=float)
[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]

Array using np.eye(N= no.of.row, M= no.of.column, k=0)
[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Empty array without initializing elements
[[0.15987732 0.14384308]
 [0.44601534 0.70760803]
 [0.03833358 0.51824214]
 [0.40451634 0.99140559]
 [0.77779761 0.09728929]]

Full array using np.full(shape, fill_value, dtype=None)
[[8 8 8]
 [8 8 8]]

 [[3 8]
 [3 8]
 [3 8]
 [3 8]
 [3 8]]

 [[3 8]
 [9 2]
 [3 8]
 [9 2]
 [1 1]]

Creating a random array using np.random.rand()
[[0.21762945 0.5352883 ]
 [0.51323204 0.82597318]
 [0.99857004 0.48505474]
 [0.68675667 0.69855079]
 [0.07542479 0.74159909]]

 [[[0.30386456 0.57837939 0.06108156]
  [0.67605484 0.75323263 0.088514  ]
  [0.07202638 0.14589452 

### upcasting

In [6]:
# when a numpy array consist of elements of different datatype upcasting can be done
# Upcasting is the process of converting all the elements of the array to higher oreder element
# The upcasting hireracy follows int --> float --> complex --> object
# Upcasting happens automatically in NumPy and that can also be user contolled

# NumPy has following datatypes that can be assigned when declaring an array
    # i - integer (i1 - int8, i2 - int16, i4 - int32, i8 - int64)
    # b - boolean
    # u - unsigned integer
    # f - float
    # c - complex
    # m - timedelta
    # M - datetime
    # O - object
    # S - string
    # U - unicode string
    # V - fixed chunk of memory for other type ( void )
    
# For i, u, f, S and U we can define size as well. (ie., i4, u8 etc..)
# i4 represents 4byte integer

In [7]:
lst = [20, 30, 25.6, 56]         # Hetrogeneous list contains int and float
farr = np.array(lst)             # creating numpy array
iarr = np.array(lst, dtype='i2') # creating numpy array of int datatype with hetrogeneous list object
sarr = np.array(lst, dtype='S')  # creating numpy array of string datatype with hetrogeneous list object
print(farr, farr.dtype)          # Automatic upcasting happened
print(iarr, iarr.dtype)          # Manual upcasting to int
print(sarr, sarr.dtype)          # Manual upcasting to string

[20.  30.  25.6 56. ] float64
[20 30 25 56] int16
[b'20' b'30' b'25.6' b'56'] |S4


In [8]:
# converting datatype of existing array

carr = sarr.astype('f8')  # use as type to change the datatype of exixting array
print(carr, carr.dtype)

[20.  30.  25.6 56. ] float64


### Array dimensions

In [12]:
# Zero dimensional array (0-D Array)

# 0-D array can be defined as scalars, every individual of the array is a 0-D array.

zero_arr = np.array('hello')
print(zero_arr)
print('numbers of dimension =',zero_arr.ndim)  # to check no.of dimension use 'var.ndim'

hello
numbers of dimension = 0


In [16]:
# One dimensional array (1-D Array)

# Array that has more than one 0-D array is called as 1-D Array

one_arr = np.array([1,2,3,4])
print(one_arr)
print('numbers of dimension =',one_arr.ndim) # to check no.of dimension use 'var.ndim'

[1 2 3 4]
numbers of dimension = 1


In [20]:
# Two dimensional array (2-D Array)

# Array with more than one 1-D array is called as 2-D array. This is alsop called as matrices.

two_arr = np.array([[1,2,3,4],[5,6,7,8],[8,9,10,11]])
print(two_arr)
print('numbers of dimension =',two_arr.ndim) # to check no.of dimension use 'var.ndim'

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 8  9 10 11]]
numbers of dimension = 2


In [28]:
# Three dimensional array (3-D Array)

# Array with more than one 2-D array is called as 3-D array

three_arr = np.array([
    [[1,2,0],[3,4,0]],
    [[5,6,0],[7,8,0]]
])
print(three_arr)
print('numbers of dimension =',three_arr.ndim) # to check no.of dimension use 'var.ndim'

[[[1 2 0]
  [3 4 0]]

 [[5 6 0]
  [7 8 0]]]
numbers of dimension = 3


In [40]:
# Higher dimensional array

# 1-D, 2-D, 3-D are the most commonly used array types
# but array can be of any dimension
# number of dimensions can be assigned using ndmin argument

ndim_arr = np.array([[2,3,4],[5,6,7]], ndmin=5)
print(ndim_arr)
print('numbers of dimension =',ndim_arr.ndim) 

[[[[[2 3 4]
    [5 6 7]]]]]
numbers of dimension = 5


### shape and size of an array

In [60]:
# shape --> returns tuple with shape of the array

# two dimensional array
sarr = np.array([[14,15,16],[20,23,26]])
print(sarr.shape)  # Output represents that the array has 2 rows and 3 columns

# three dimensional array
tarr = np.array([[[14,15,16],[20,23,26]],[[14,15,16],[20,23,26]],[[14,15,16],[20,23,26]],[[14,15,16],[20,23,26]]])
print(tarr.shape) # output represents that tha array has 4 block size and each layes has 2 rows and 3 columns

# one dimensional array
oarr = np.array([25,56,78])
print(oarr.shape)  # output represents that the array has 1 row and 3 columns

# for 1-D array the shape attribute returns the columns alone (ie.,(no.of.columns,))

(2, 3)
(4, 2, 3)
(3,)


In [188]:
# reshape --> process of changing the shape of an array

# to reshape a array the number of elements should be equal to the product of rows and columns

rsarr = np.arange(1,13)      # 12 elements in the array
print('\n',rsarr.reshape(2,6))    # 2-D array
print('\n',rsarr.reshape(2,2,3))  # 3-D array (product of block size, rows and column = no.of.elements)
print('\n',rsarr.reshape(6,-1))   # -1 solves itself for the unknown product 

rsarr2 = np.array([[[2,3],[2,4],[5,6]],[[2,3],[2,4],[5,6]]])
print('\n',rsarr2.reshape(-1))      # reshape(-1) flatternes the multidimensional array


 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]

 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]

 [2 3 2 4 5 6 2 3 2 4 5 6]


In [68]:
# size --> returns int with the number of elements that an array has

print(sarr.size)
print(tarr.size)
print(oarr.size)

6
24
3


In [25]:
# Creating a transpose of a array (transpose matrix)

ar1 = np.array([[2,3,4],[4,5,6],[7,8,9]])
print('Non transpose 2D matrix:')
print(ar1)
print('\nTranspose 2D matrix:')
print(ar1.T)

# Tranpose can also be done three dimensional array

ar2 = np.array([[[1,2,3],[4,5,6]],[[10,20,30],[40,50,60]]])
print('\nNon transpose 3D matrix:')
print(ar2)
print('\nTranspose 3Dmatrix:')
print(ar2.T)

# 1D array cant be transposed because it is a scalar unit and its not a matrix

Non transpose 2D matrix:
[[2 3 4]
 [4 5 6]
 [7 8 9]]

Transpose 2D matrix:
[[2 4 7]
 [3 5 8]
 [4 6 9]]

Non transpose 3D matrix:
[[[ 1  2  3]
  [ 4  5  6]]

 [[10 20 30]
  [40 50 60]]]

Transpose 3Dmatrix:
[[[ 1 10]
  [ 4 40]]

 [[ 2 20]
  [ 5 50]]

 [[ 3 30]
  [ 6 60]]]


### Basic oprations in an array


In [28]:
# Array can handle all the element level and array level arithematic operation
# For performing operation between two array the length of both array has to be same.

oar1 = np.arange(5)
oar2 = np.arange(6,11)


In [43]:
# Element level operation

print(f'Addition of {oar1} and 2 is {oar1+2}')
print(f'Subtraction of {oar1} and 2 is {oar1-2}')
print(f'Multiplication of {oar1} and 2 is {oar1*2}')
print(f'Division of {oar1} and 2 is {oar1/2}')
print(f'Floor division of {oar1} and 2 is {oar1//2}')
print(f'Modulo of {oar1} and 2 is {oar1%2}')
print(f'{oar1} to the power of 2 is {oar1**2}')

Addition of [0 1 2 3 4] and 2 is [2 3 4 5 6]
Subtraction of [0 1 2 3 4] and 2 is [-2 -1  0  1  2]
Multiplication of [0 1 2 3 4] and 2 is [0 2 4 6 8]
Division of [0 1 2 3 4] and 2 is [0.  0.5 1.  1.5 2. ]
Floor division of [0 1 2 3 4] and 2 is [0 0 1 1 2]
Modulo of [0 1 2 3 4] and 2 is [0 1 0 1 0]
[0 1 2 3 4] to the power of 2 is [ 0  1  4  9 16]


In [37]:
# Operation between array

print(f'Addition of {oar1} and {oar2} is {oar1+oar2}')
print(f'Subtraction of {oar1} and {oar2} is {oar1-oar2}')
print(f'Multiplication of {oar1} and {oar2} is {oar1*oar2}')
print(f'Division of {oar1} and {oar2} is {oar1/oar2}')
print(f'Floor division of {oar1} and {oar2} is {oar1//oar2}')
print(f'Modulo of {oar1} and {oar2} is {oar1%oar2}')
print(f'{oar1} to the power {oar2} is {oar1**oar2}')

Addition of [0 1 2 3 4] and [ 6  7  8  9 10] is [ 6  8 10 12 14]
Subtraction of [0 1 2 3 4] and [ 6  7  8  9 10] is [-6 -6 -6 -6 -6]
Multiplication of [0 1 2 3 4] and [ 6  7  8  9 10] is [ 0  7 16 27 40]
Division of [0 1 2 3 4] and [ 6  7  8  9 10] is [0.         0.14285714 0.25       0.33333333 0.4       ]
Floor division of [0 1 2 3 4] and [ 6  7  8  9 10] is [0 0 0 0 0]
Modulo of [0 1 2 3 4] and [ 6  7  8  9 10] is [0 1 2 3 4]
[0 1 2 3 4] power [ 6  7  8  9 10] is [      0       1     256   19683 1048576]


In [70]:
# Scalar multiplication:

scm1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
scm2 = np.zeros((3,3), dtype= int)+2
print(scm1*scm2)
print(scm1*5)
# To perform scalar multiplication the number of rows and colums should be equal or it has to be single element
# In scalar multiplication (3*5) and (5*8) is a ValueError

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


In [81]:
# Vector multiplication 

print(scm1.dot(scm2))
# To perform vector multiplication no of columns in 1 array should match the no of rows in next array
# Or it has to be single element
# In vector multiplication (3*5) and (5*8) is (3*8)
# Example:
print('\n',(np.zeros((3,5),dtype=int).dot(np.zeros((5,8),dtype=int))).shape)

[[12 12 12]
 [30 30 30]
 [48 48 48]]

 (3, 8)


### Unary operation

In [12]:
import numpy as np
uar1 = np.array([10,20,30,40])
uar2 = np.array([1,2,3,4])

# To add two array using add function
print('Adding two array',np.add(uar1,uar2))

# To add subtract two array using subtract function
print('Subtract two array',np.subtract(uar1,uar2))

# To multiply two array using multiply function
print('Multilpy two array',np.multiply(uar1,uar2))

# To divide two array using divide function
print('Divide two array',np.divide(uar1,uar2))

# To power two array using power function
print('Power of array',np.power(uar1,uar2))

# To find the reminder of two array using remainder or mod function
print('Reminder of array using mod',np.mod(uar1,uar2))
print('Reminder of array using remainder',np.remainder(uar1,uar2))

# To find the quotient of two array using divmod function
print('Quotient of array',np.divmod(uar1,uar2))

# To change the array to absolute array
print('Absolute of the array is', np.absolute(np.array([-1,-2,-5,6,7,-8,-52])))

# To find the mean of an array
print('Mean value of the array is', np.mean((uar1, uar2)))

# To find the meadian of an array
print('Median value of the array is', np.median((uar1, uar2)))

# To find the standard deviation of an array
print('Standard deviation value of the array is', np.std((uar1, uar2)))

# To find the variance of an array
print('Variance value of the array is', np.var((uar1, uar2)))

Adding two array [11 22 33 44]
Subtract two array [ 9 18 27 36]
Multilpy two array [ 10  40  90 160]
Divide two array [10. 10. 10. 10.]
Power of array [     10     400   27000 2560000]
Reminder of array using mod [0 0 0 0]
Reminder of array using remainder [0 0 0 0]
Quotient of array (array([10, 10, 10, 10]), array([0, 0, 0, 0]))
Absolute of the array is [ 1  2  5  6  7  8 52]
Mean value of the array is 13.75
Median value of the array is 7.0
Standard deviation value of the array is 13.77270852083932
Variance value of the array is 189.6875


In [87]:
# Rounding Decimals

# Truncating the decimals
print('Truncating 1.6251 is equal to', np.trunc(1.6251))

# Rounding off to nearest decimal
print('Rounding of 2.322 and 2.866 is eqal to', np.around((2.322,2.866), decimals=1))

# Flooring the decimal
print('Floor of 2.322 and 2.866 is eqal to', np.floor((2.322,2.866)))

# Ceiling the decimal
print('Ceil of 2.322 and 2.866 is eqal to', np.array(np.ceil((2.322,2.866)),dtype=int))

Truncating 1.6251 is equal to 1.0
Rounding of 2.322 and 2.866 is eqal to [2.3 2.9]
Floor of 2.322 and 2.866 is eqal to [2. 2.]
Ceil of 2.322 and 2.866 is eqal to [3 3]


### Indexing and slicing

In [97]:
# Indexing and slicing in 1D array
iar1 = np.array([10,20,30,40,50,60])

print('Third index of an array is',iar1[3])
print('Last index of an array is',iar1[-1])
print('Slicing from first to third index is',iar1[1:4])
print('Reversing the array by slicing',iar1[::-1])
print('Reversing slicing by step two',iar1[::-2])
print('Reverse slicing the required elements',iar1[4:1:-1])
print('Reverse slicing the required elements',iar1[-2:-5:-2])
print('Slicing by step two',iar1[::2])

Third index of an array is 40
Last index of an array is 60
Slicing from first to third index is [20 30 40]
Reversing the array by slicing [60 50 40 30 20 10]
Reversing slicing by step two [60 40 20]
Reverse slicing the required elements [50 40 30]
Reverse slicing the required elements [50 30]
Slicing by step two [10 30 50]


In [183]:
# Indexing and slicing in 2D array

iar2 = np.arange(1,17).reshape(4,4)
print(iar2)

# indexing
print('\nIndexing of matrix/2D array: ')
print('Fourth element of first row is', iar2[0,3])
print('First element of second row is', iar2[1,0])
print('Last element of first row is', iar2[0,-1])
print('Last element of second row is', iar2[1,-1])
print('Last element of last row is', iar2[-1,-1])

# slicing
print('\nSlicing of matrix/2D array: ')
print('Slicing the first row of the matrix', iar2[:1])
print('Slicing the second row of the matrix', iar2[1:2])
print('Slicing the fourth row of the matrix', iar2[3:4])
print('Slicing the first two rows of the matrix\n', iar2[:2])
print('Slicing the last two rows of the matrix\n', iar2[-2:])
print('Slicing third row 2nd element of the matrix', iar2[2:3,1])
print('Slicing middle rows and middle element of the matrix\n', iar2[1:3,1:3])
print('Slicing second and fourth column of the matrix\n', iar2[::,1::2])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Indexing of matrix/2D array: 
Fourth element of first row is 4
First element of second row is 5
Last element of first row is 4
Last element of second row is 8
Last element of last row is 16

Slicing of matrix/2D array: 
Slicing the first row of the matrix [[1 2 3 4]]
Slicing the second row of the matrix [[5 6 7 8]]
Slicing the fourth row of the matrix [[13 14 15 16]]
Slicing the first two rows of the matrix
 [[1 2 3 4]
 [5 6 7 8]]
Slicing the last two rows of the matrix
 [[ 9 10 11 12]
 [13 14 15 16]]
Slicing third row 2nd element of the matrix [10]
Slicing middle rows and middle element of the matrix
 [[ 6  7]
 [10 11]]
Slicing second and fourth column of the matrix
 [[ 2  4]
 [ 6  8]
 [10 12]
 [14 16]]


In [190]:
# Extracting the diagonal values from a matrix

dnr = np.arange(36).reshape(6,6)
print('Elements of the first diagonal are',dnr[(np.eye(6))==1])
print('Elements of the second diagonal are',dnr[(np.eye(6)[::-1])==1])

Elements of the first diagonal are [ 0  7 14 21 28 35]
Elements of the second diagonal are [ 5 10 15 20 25 30]


### Performing operation along the axis

In [15]:
axa = np.arange(36).reshape(6,6)
print(s)
print('\nAdding the elements in rows', np.sum(axa, axis=1))
print('Adding the elements in columns', np.sum(axa, axis=0))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]

Adding the elements in rows [ 15  51  87 123 159 195]
Adding the elements in columns [ 90  96 102 108 114 120]


### Iterating over the array

In [28]:
iar = np.arange(25).reshape(5,5)

# printing the rows of the array
cnt = 0
for i in iar:
    cnt += 1
    print('Printing row '+str(cnt),'=',i)

Printing row 1 = [0 1 2 3 4]
Printing row 2 = [5 6 7 8 9]
Printing row 3 = [10 11 12 13 14]
Printing row 4 = [15 16 17 18 19]
Printing row 5 = [20 21 22 23 24]


In [30]:
# To store the elements of the array to a list
lst = []
for row in iar:
    for ele in row:
        lst.append(ele)
print(lst)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]


In [46]:
for i in iar:
    for j in i:
        if j in [10,20,30]:
            print(j,'is in the list')
print()            
# ------ or use below code ----

for i in iar.flatten():
    if i in [10,20,30]:
        print(i, 'is in the list')

10 is in the list
20 is in the list

10 is in the list
20 is in the list
